### ISSUE TITLE
Feature request: disable events in dropdown when events are disabled

### ISSUE THREAD

**Issue by endredavids** [flow-ai/platform#20]
#### I'm submitting a ...
- feature request
 

#### What is the current behavior?
Events that are disabled, are still being shown in the dropdown on the right. Would be usefull if the user can only link to active events.   
 

#### What is the expected behavior?
see above
 

#### Please tell us about your environment:

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari]
- OS: [all | Windows X.X | macOS | iOS ]

**Comment by Geeza** [comment]
Good UX improvement. Ideally you can still select them but you'll have a clear indication that these are "disabled"

**Comment by Geeza** [comment]
We made it so that disabled events can still be selected but are shown within a "disabled" section of the drop down
