### ISSUE TITLE
Track your chatbot in Google Analytics (simple version)

### ISSUE THREAD

**Issue by jmchat** [flow-ai/platform#22]
#### I'm submitting a ...
- feature request
 
#### What is the current behavior?
No tracking possibilities with Google Analytics or any other statistics software.

#### What is the expected behavior?
A connection with Google Analytics to see which flows and triggers are used.

Documentation about GA events:
https://developers.google.com/analytics/devguides/collection/analyticsjs/events
 
This could be filled as followed:
EventCategory: Trigger of Text
EventAction: Flow Title (or the metadata)
eventLabel: Channel (Web, Messenger, Google, etc.)
eventvalue: none

#### What is the motivation/use case for changing the behavior?
To get more basic insights on how the bot is performing

**Comment by sneerin** [comment]
@jmchat do you need only google analytics or other chatbot analytics tools might be good for you?

**Comment by jmchat** [comment]
I think GA is a nice and simple start but it would be better if you could connect with https://chatbase.com/welcome/products/virtual-agent-analytics/. Cause then you can really improve your bot.

GA is just to see some overal usage statistics of flows and triggers.

**Comment by sneerin** [comment]
@jmchat is that looks useful for you https://botanalytics.co/

**Comment by jmchat** [comment]
@sneerin from what I can see on both websites I must say that Chatbase looks better :-). But I don't know the differences when it comes to integration. If it's possible I prefer Chatbase.

**Comment by Geeza** [comment]
We are planning this for the sprint of March 4th
