### ISSUE TITLE
Enable/Disable upload button in webwidget

### ISSUE THREAD

**Issue by bakker2105** [flow-ai/platform#24]
**Note: for support questions, please use [slack](https://slack.flow.ai)**. This repository's issues are reserved for feature requests and bug reports.

#### I'm submitting a ...
feature request
 

#### What is the current behavior?
upload button is by default available in webwidget
 

#### What is the expected behavior?
Add a setting to the backend to enable of disable the upload button (the paperclip)
 

#### What is the motivation/use case for changing the behavior?
Sometimes it is not desirable to give an upload option
 

#### Please tell us about your environment:

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari]
- OS: [all | Windows X.X | macOS | iOS ]

**Comment by Geeza** [comment]
Should be easy to do and part of the web widget configuration. No ETA yet, but will be picked up next few months

**Comment by Geeza** [comment]
This is fixed and will be available in the next few days
