### ISSUE TITLE
Use trigger in chat does not work

### ISSUE THREAD

**Issue by jmchat** [flow-ai/platform#26]
#### I'm submitting a ...
- bug report

#### What is the current behavior?
When you select:
USE IN CHAT
This will allow a customer service agent to trigger event from the Chat app
 
And then hit Save the checkbox is still not active.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshot of the problem:
Open a flow with a Trigger to test this.

#### What is the expected behavior?
After hitting Save the checkbox must still be active!

#### Please tell us about your environment:

- Browser: [all]
- OS: [all]

**Comment by Geeza** [comment]
Thank you for reporting. This is being fixed as we speak

**Comment by jmchat** [comment]
Saving the item works, but using it in chat chat does not :-).

After the event is added the widget does not now the answer/action to make

**Comment by sneerin** [comment]
It’s about to be deployed. Since deploy can cause clients disconnect the final fix is postponed till late evening.
