### ISSUE TITLE
Found entities in Payload

### ISSUE THREAD

**Issue by jmchat** [flow-ai/platform#27]
#### I'm submitting a ...
- feature request
 
#### What is the current behavior?
Found entities won't show up in the payload

#### What is the expected behavior?
Extend the Payload with found entities

#### What is the motivation/use case for changing the behavior?
To build a smarter catch all when the bot don't know the answer.

**Comment by Geeza** [comment]
We'll investigate the impact of the change.

**Comment by Geeza** [comment]
We'll add any found entities inside the `payload.match`. So `payload.match.entities` would be an object with any entities it found (and corresponding values)
